#!/bin/bash

# The file where we will write our messages
OUTPUT_FILE="/tmp/my_process"

# Function to write to the output file
write_alive() {
    while true; do
        echo "I am alive!" >> "$OUTPUT_FILE"
        sleep 2
    done
}

# Start the process
write_alive &
# Save the PID of the background process
echo $! > /var/run/my_process.pid

